---

- name: Deploy BeeGFS license file
  ansible.builtin.copy:
    content: "{{ beegfs_license_content }}"
    dest: /etc/beegfs/license.pem
    mode: "0600"
    owner: root
    group: root
  become: true
  no_log: true
  when: beegfs_license_content | default('') | length > 0

- name: Disable TLS authentication (Development)
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-mgmtd.toml
    insertafter: "^# tls-disable ="
    regexp: "^tls-disable ="
    line: "tls-disable = {{ beegfs_disable_tls | lower }}"
  become: true
  notify: Restart BeeGFS mgmt service

- name: Adapt database file location
  ansible.builtin.lineinfile:
    path: /etc/beegfs/beegfs-mgmtd.toml
    regexp: "^db-file ="
    line: "db-file = '{{ beegfs_mgmt_path }}/mgmtd.sqlite'"
    insertafter: "^# db-file ="
  become: true
  notify: Restart BeeGFS mgmt service

- name: Run management service setup script
  ansible.builtin.command: "/opt/beegfs/sbin/beegfs-mgmtd --init"
  args:
    creates: "{{ beegfs_mgmt_path }}/mgmtd.sqlite"
  become: true
  notify: Restart BeeGFS mgmt service
