---
- name: Ensure RDMA kernel modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  become: true
  loop:
    - "ib_umad"
    - "ib_uverbs"
    - "rdma_ucm"
