---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    image: centos:7
    pre_build_image: true
  - name: instance-stream8-${INSTANCE_ID:-local}
    image: quay.io/centos/centos:stream8
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
