# Make sure that SLURM repo is available
---
- name: Install SLURM package
  hosts: all
  vars:
    role_slurm_version: 25.11.2-1.el{{ansible_distribution_major_version}}
  tasks:

      # due to https://github.com/geerlingguy/docker-rockylinux9-ansible/issues/6
    - name: Ensure /etc/shadow has correct permissions
      ansible.builtin.file:
        path: /etc/shadow
        mode: '0400'

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - epel-release
          - hostname
          - python3-dnf-plugin-versionlock
          - openssh-server
          - sudo
          # - "{{ (ansible_distribution_major_version == '7') | ternary('policycoreutils-python', 'policycoreutils-python-utils') }}"
        state: installed

    - name: Setup artifactory
      vars:
        os_distro: "{{ ((centos_release['content'] | b64decode).find('Stream') != -1) | ternary('stream', 'centos') }}"
      ansible.builtin.yum_repository:
        name: artifactory
        description: Artifactory slurm RPM repo
        file: external_repos
        baseurl: https://artifactory.imp.ac.at/localSLURM/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}
        gpgcheck: false

    - name: Lock the version of slurm
      community.general.dnf_versionlock:
        name:
          - slurm*-{{ role_slurm_version }}
