---
- name: Test some services on all nodes
  hosts: all
  become: true
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if munge service is running and enabled
      ansible.builtin.assert:
        that:
          - "'munge.service' in services"
          - services['munge.service'].state == 'running'
          - services['munge.service'].status == 'enabled'
        fail_msg: "Munge service is not running and enabled"


- name: Import REST API test playbook
  ansible.builtin.import_playbook: test_rest.yml

- name: Import Compute test playbook
  ansible.builtin.import_playbook: test_compute.yml

- name: Import DB test playbook
  ansible.builtin.import_playbook: test_db.yml

- name: Import Runtime test playbook
  ansible.builtin.import_playbook: test_runtime.yml
