---
- name: Converge
  hosts: all
  vars:
    op_service_account_token: "{{ lookup('env', 'OP_SERVICE_ACCOUNT_TOKEN') }}"
  tasks:
    - name: Install pip libraries
      ansible.builtin.command: pip3 install infoblox-client
      delegate_to: localhost
      changed_when: false

    - name: Setup host certificate
      vars:
        base_domain: vbc.ac.at
        role_certificate_hostname: cert-sectigo-test-1.{{ base_domain }}
        role_certificate_aliases:
          - "*.wildcard.cert-sectigo-test-1.{{ base_domain }}"
          - san1-sectigo-test.{{ base_domain }}
        role_certificate_tls_dir: /srv/certificates/
        role_certificate_provider:
          type: acme
          directory: "{{ lookup('onepassword', 'sectigo_molecule', field='url', vault='accounts', \
            service_account_token=op_service_account_token) }}"
          account_id: "{{ lookup('onepassword', 'sectigo_molecule', field='account_id', vault='accounts', \
            service_account_token=op_service_account_token) }}"
          account_uri: "{{  lookup('onepassword', 'sectigo_molecule', field='url', vault='accounts', \
            service_account_token=op_service_account_token) }}/account/{{  lookup('onepassword', 'sectigo_molecule', field='account_id', vault='accounts', \
            service_account_token=op_service_account_token) }}"
          account_key: "{{  lookup('onepassword', 'sectigo_molecule', field='key', vault='accounts', \
            service_account_token=op_service_account_token) | b64decode }}"
        role_certificate_renew_days: 31
        role_certificate_nios_provider:
          host: ns.imp.ac.at
          username: svc_infoblox_ansible
          password: "{{ lookup('onepassword', 'linux_baseline', section='dns-nios', field='password', vault='hosts', \
            service_account_token=op_service_account_token) }}"
      ansible.builtin.include_role:
        name: certificate
