---
- name: Un-enroll machine
  hosts: all
  gather_facts: false
  vars_files:
    - ../../vars/main.yml
  vars:
    ad_password: "{{ lookup('onepassword', 'svc_realmd_test_join', vault='accounts', master_password=onepass_password, secret_key=onepass_secret_key, subdomain=onepass_domain,\
      \ username=onepass_email) }}"
  tasks:
    - name: Un-enroll machines
      changed_when: false
      ansible.builtin.shell: echo {{ ad_password }} | realm leave --unattended --verbose -U {{ role_sssd_domains.TESTING.ad_username }} {{ role_sssd_domains.TESTING.name }}
      ignore_errors: true
