---
- name: Prepare all
  hosts: all
  gather_facts: false
  tasks:
  # add pgrep, iproute for ss tool, to run testinfra.
    - name: Install iproute and pgrep for testing
      become: true
      ansible.builtin.yum:
        name: iproute,net-tools,tcpdump,procps-ng
        state: present

# we assume rsyslog will be present everywhere, for testing we have to prepare it
- name: Prepare client
  hosts: syslog-client
  gather_facts: false
  become: true
  tasks:
    - name: Install rsyslog
      ansible.builtin.yum:
        name: rsyslog
        state: present
    - name: Start rsyslog
      ansible.builtin.systemd:
        name: rsyslog.service
        enabled: true
        daemon_reload: true
        state: started
