---
- name: send client messages
  hosts: syslog-client
  gather_facts: false
  tasks:
    # add iproute for ss tool, to run testinfra
    - name: send example log messages
      changed_when: false
      command: /bin/logger -p {{ item.prio }} -t {{ item.tag | default('testlog') }} '{{ item.msg }} with {{ item.prio }}'
      loop:
        - prio: info
          msg: hello world
        - prio: info
          msg: hello all the protos
        - prio: crit
          msg: this is critical
        - prio: emerg
          msg: this is SO BAD
        - prio: info
          tag: nginx
          msg: http GET me this thing

- name: flush server buffers
  hosts: syslog-server
  gather_facts: false
  become: true
  tasks:
    - name: HUP rsyslogd
      changed_when: false
      shell: kill -HUP $(pgrep rsyslogd)
