---
dependency:
  name: galaxy
driver:
  name: docker
  network:
    - name: "slurm-stream8-${INSTANCE_ID:-local}"
      driver: bridge
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "login-stream8-${INSTANCE_ID:-local}"
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    hostname: "cluster-login-0"
    networks:
      - name: "slurm-stream8-${INSTANCE_ID:-local}"
        links:
          - "compute1-stream8-${INSTANCE_ID:-local}:cluster-compute1-0"
          - "compute2-stream8-${INSTANCE_ID:-local}:cluster-compute2-0"
    groups:
      - cluster_login
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: "compute1-stream8-${INSTANCE_ID:-local}"
    hostname: "cluster-compute1-0"
    pre_build_image: true
    networks:
      - name: "slurm-stream8-${INSTANCE_ID:-local}"
    image: quay.io/centos/centos:stream8
    groups:
      - cluster_batch
    children:
      - cluster_compute1
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: "compute2-stream8-${INSTANCE_ID:-local}"
    hostname: "cluster-compute2-0"
    pre_build_image: true
    networks:
      - name: "slurm-stream8-${INSTANCE_ID:-local}"
    image: quay.io/centos/centos:stream8
    groups:
      - cluster_batch
    children:
      - cluster_compute2
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: "control-stream8-${INSTANCE_ID:-local}"
    pre_build_image: true
    networks:
      - name: "slurm-stream8-${INSTANCE_ID:-local}"
        links:
          - "compute1-stream8-${INSTANCE_ID:-local}:cluster-compute1-0"
          - "compute2-stream8-${INSTANCE_ID:-local}:cluster-compute2-0"
    image: quay.io/centos/centos:stream8
    groups:
      - cluster_control
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: "db-stream8-${INSTANCE_ID:-local}"
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    networks:
      - name: "slurm-stream8-${INSTANCE_ID:-local}"
    groups:
      - cluster_db
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
scenario:
  name: stream8
verifier:
  name: testinfra
  directory: ../resources/tests/
