---
- name: Converge
  hosts: all
  gather_facts: false

  vars:
    role_container_service:
      name: webservice
      image: docker.artifactory.imp.ac.at/it/molecule/tests/httpd
      tag: 2.4.39-alpine
      uid: 222
      gid: 333
      hostname: it-webserver-1.vbc.ac.at
      certificate: true
      selinux: true
    role_container_hostname: it-webserver-1.vbc.ac.at

  pre_tasks:
    - name: Install SSL libraries for RHEL8
      become: true
      yum:
        name: python3-cryptography
        state: present
        update_cache: true
    - name: Create fake certificate directory
      become: true
      file:
        path: /srv/certificates
        state: directory
        owner: root
        group: root
        mode: "0550"
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      become: true
      openssl_privatekey:
        path: /srv/certificates/it-webserver-1.vbc.ac.at.key
    - name: Generate an OpenSSL Certificate Signing Request
      become: true
      openssl_csr:
        path: /srv/certificates/it-webserver-1.vbc.ac.at.csr
        privatekey_path: /srv/certificates/it-webserver-1.vbc.ac.at.key
        common_name: it-webserver-1.vbc.ac.at
    - name: Generate a Self Signed OpenSSL certificate
      become: true
      openssl_certificate:
        path: /srv/certificates/it-webserver-1.vbc.ac.at.crt
        privatekey_path: /srv/certificates/it-webserver-1.vbc.ac.at.key
        csr_path: /srv/certificates/it-webserver-1.vbc.ac.at.csr
        provider: selfsigned
  tasks:
    - name: Include container role
      include_role:
        name: container
