---
- name: Check variables
  assert:
    that:
      - role_base_user_publickey_username | length > 0
      - role_base_user_publickey_key | length > 0
      - role_base_user_linux_username | length > 0
      - role_base_user_linux_password | length > 0

- name: Create group for the ansible tower user
  become: true
  group:
    name: "{{ role_base_user_publickey_username }}"
    state: present
    gid: 100000

- name: Create ansible tower automation user (role_base_user_publickey_username / role_base_user_publickey_key)
  become: true
  user:
    name: "{{ role_base_user_publickey_username }}"
    comment: Managed by tower
    uid: 100000
    group: "{{ role_base_user_publickey_username }}"
    shell: /bin/bash
    state: present
    create_home: true
    home: /home/{{ role_base_user_publickey_username }}
    append: true

- name: Create group for the fallback user
  become: true
  group:
    name: "{{ role_base_user_linux_username }}"
    state: present
    gid: 100001

- name: Create fallback user (role_base_user_linux_username / role_base_user_linux_password)
  become: true
  user:
    name: "{{ role_base_user_linux_username }}"
    comment: Managed by tower
    uid: 100001
    group: "{{ role_base_user_linux_username }}"
    shell: /bin/bash
    state: present
    create_home: true
    home: /home/{{ role_base_user_linux_username }}
    groups: wheel
    append: true
    password: "{{ role_base_user_linux_password | password_hash('sha512', role_base_user_linux_salt) }}"

- name: Set up authorized keys for the ansible user (role_base_user_publickey_username)
  become: true
  authorized_key:
    user: "{{ role_base_user_publickey_username }}"
    key: "{{ item }}"
  with_items: "{{ role_base_user_publickey_key }}"

- name: Set passwordless root for ansible user (role_base_user_linux_username)
  become: true
  lineinfile:
    dest: /etc/sudoers.d/system_deployment_{{ role_base_user_linux_username }}
    state: present
    create: true
    mode: "0644"
    line: "{{ role_base_user_linux_username }} ALL=(ALL) NOPASSWD: ALL"

- name: Set passwordless root for ansible user (role_base_user_publickey_username)
  become: true
  lineinfile:
    dest: /etc/sudoers.d/system_deployment_{{ role_base_user_publickey_username }}
    state: present
    create: true
    mode: "0644"
    line: "{{ role_base_user_publickey_username }} ALL=(ALL) NOPASSWD: ALL"

- name: Disable ssh root login (just in case)
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin "
    line: PermitRootLogin no
  notify: restart-sshd

- name: Disable ssh login for fallback user (role_base_user_linux_username)
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: DenyUsers {{ role_base_user_linux_username }}
  notify: restart-sshd
