---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    image: centos/systemd:latest
    pre_build_image: true
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: instance-stream8-${INSTANCE_ID:-local}
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
