---
# handlers file for role-goss
- name: Restart goss
  ansible.builtin.systemd:
    daemon_reload: true
    name: goss
    state: restarted
  when: goss_run_as_service
  tags:
    - always
    - goss_reconfigure
