---
- name: Install SLURM compute image packages
  yum:
    name:
      - "libicu"
      - "numactl"
      - "slurm-pam_slurm"
      - "slurm-libpmi"
    state: installed

- name: Select the SLURM service to control
  set_fact:
    role_slurm_service: slurmd
