---
- name: Install SLURM compute image packages
  ansible.builtin.yum:
    name:
      - libicu
      - numactl
      - slurm-pam_slurm
      - slurm-libpmi
    state: installed

- name: Select the SLURM service to control
  ansible.builtin.set_fact:
    role_slurm_service: slurmd
