---
- name: Install SLURM controller packages
  ansible.builtin.yum:
    name:
      - slurm-devel
      - slurm-perlapi
      - slurm-slurmctld
      - slurm-example-configs
      - "{{ (ansible_distribution_major_version == '7') | ternary('mailx', 's-nail') }}"
    state: installed

- name: Select the SLURM service to control
  ansible.builtin.set_fact:
    role_slurm_service: slurmctld

- name: Configure powersaving
  ansible.builtin.import_tasks: powersave.yml
  when: role_slurm_power_save | bool
