---

- name: control | Create State Save directory
  tags:
    - control
    - reconfigure
  ansible.builtin.file:
    path: "{{ slurm_state_save_location }}"
    state: directory
    mode: "0755"
    owner: slurm
    group: slurm


- name: control | Template job_container.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: job_container.conf.j2
    dest: /etc/slurm/job_container.conf
    mode: "0644" # perms/ownership based off src from ohpc package
    owner: root
    group: root

- name: control | Template slurm.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart slurmctld service
    - Reconfigure slurmctld
  register: slurm_conf
  # NB uses restart rather than reload as number of nodes might have changed

- name: control | Create gres.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: "gres.conf.j2"
    dest: /etc/slurm/gres.conf
    mode: "0600"
    owner: slurm
    group: slurm
  notify:
    - Restart slurmctld service
    - Reconfigure slurmctld
  register: slurm_gres_conf
  # NB uses restart rather than reload as this is needed in some cases

- name: control | Template cgroup.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    mode: "0644" # perms/ownership based off src from ohpc package
    owner: root
    group: root

- name: control | Configure powersaving
  ansible.builtin.import_tasks: powersave.yml
  when: slurm_power_save | default(false) | bool

- name: Add QOS to Cluster
  ansible.builtin.include_tasks: qos.yml
  tags:
    - qos
    - reconfigure
    - control
    

- name: control | Ensure slurmctld state
  tags:
    - control
    - reconfigure
  ansible.builtin.service:
    name: slurmctld
    enabled: "{{ slurm_service_enabled | bool }}"
    state: "{{ 'started' if slurm_service_started | bool else 'stopped' }}"
