---

- name: control | Create State Save directory
  tags:
    - control
    - reconfigure
  ansible.builtin.file:
    path: "{{ slurm_state_save_location }}"
    state: directory
    mode: "0755"
    owner: slurm
    group: slurm


- name: control | Template job_container.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: job_container.conf.j2
    dest: /etc/slurm/job_container.conf
    mode: "0644" # perms/ownership based off src from ohpc package
    owner: root
    group: root
    backup: true

- name: control | Configure job_submit.lua
  tags:
    - control
    - reconfigure
  when: slurm_job_submit_script | default('', true) | length > 0
  block:
    - name: control | Template job_submit.lua
      ansible.builtin.template:
        src: "{{ slurm_job_submit_script }}"
        dest: /etc/slurm/job_submit.lua
        owner: root
        group: root
        mode: "0644"
        backup: true
      when: not slurm_job_submit_script_symlink | bool
      notify:
        - Reconfigure slurmctld

    - name: control | Symlink job_submit.lua
      ansible.builtin.file:
        src: "{{ slurm_job_submit_script }}"
        dest: /etc/slurm/job_submit.lua
        state: link
        force: true
      when: slurm_job_submit_script_symlink | bool
      notify:
        - Reconfigure slurmctld

    - name: control | Validate job_submit.lua compiles
      ansible.builtin.command:
        cmd: /usr/bin/luac -p /etc/slurm/job_submit.lua
      register: slurm_luac_check
      changed_when: false
      failed_when: slurm_luac_check.rc != 0

- name: control | Template slurm.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Restart slurmctld service
    - Reconfigure slurmctld
  register: slurm_conf
  # NB uses restart rather than reload as number of nodes might have changed

- name: control | Template acct_gather.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: acct_gather.conf.j2
    dest: /etc/slurm/acct_gather.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify:
    - Reconfigure slurmctld
  register: slurm_acct_gather_conf
  when: >-
    ((slurm_default_config | combine(slurm_config)).get('AcctGatherEnergyType')
    not in [None, '', 'omit'])
    or
    ((slurm_default_config | combine(slurm_config)).get('AcctGatherInterconnectType')
    not in [None, '', 'omit'])

- name: control | Create gres.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: "gres.conf.j2"
    dest: /etc/slurm/gres.conf
    mode: "0600"
    owner: slurm
    group: slurm
    backup: true
  notify:
    - Restart slurmctld service
    - Reconfigure slurmctld
  register: slurm_gres_conf
  # NB uses restart rather than reload as this is needed in some cases

- name: control | Template cgroup.conf
  tags:
    - control
    - reconfigure
  ansible.builtin.template:
    src: cgroup.conf.j2
    dest: /etc/slurm/cgroup.conf
    mode: "0644" # perms/ownership based off src from ohpc package
    owner: root
    group: root
    backup: true

- name: control | Configure powersaving
  ansible.builtin.import_tasks: powersave.yml
  when: slurm_power_save | default(false) | bool

- name: control | Add QOS to Cluster
  ansible.builtin.include_tasks: qos.yml
  tags:
    - qos
    - reconfigure
    - control


- name: control | Ensure slurmctld state
  tags:
    - control
    - reconfigure
  ansible.builtin.service:
    name: slurmctld
    enabled: "{{ slurm_service_enabled | bool }}"
    state: "{{ 'started' if slurm_service_started | bool else 'stopped' }}"
