# Install SlurmDBD services and packages
---
- name: db | Create archive folder for purged DB objects
  tags: database
  ansible.builtin.file:
    state: directory
    path: "{{ slurm_dbd_archive_dir }}"
    owner: slurm
    group: root
    mode: "0750"
  when: slurm_dbd_archive_dir is defined

- name: db | Template in slurmdbd.conf
  tags:
    - database
    - reconfigure
  ansible.builtin.template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    owner: slurm
    mode: "0600"
    backup: true
  notify:
    - Restart slurmdbd service


- name: db | Ensure slurmdbd state
  tags:
    - database
    - reconfigure
  ansible.builtin.service:
    name: slurmdbd
    enabled: "{{ slurm_service_enabled | bool }}"
    state: "{{ 'started' if slurm_service_started | bool else 'stopped' }}"
