---
- name: install | Create SLURM User and Group
  tags: install
  ansible.builtin.include_tasks: users.yml

- name: install | Workaround for libjwt issue on RHEL10 (only needed for slurm REST API)
  when: ansible_distribution_major_version == '10'
  tags: install
  block:
    - name: install | Install python3-dnf-plugin-versionlock
      ansible.builtin.package:
        name: python3-dnf-plugin-versionlock
        state: present

    - name: install | Pin libjwt < 2.x.x (workaround for RHEL10 Slurm REST issue)
      community.general.dnf_versionlock:
        name:
          - libjwt-0:1*
          - libjwt-devel-0:1*

- name: install | Build host-specific list of required slurm packages
  tags: install
  ansible.builtin.set_fact:
    slurm_pkglist: "{{ (slurm_pkglist | default([])) + (item.value | default([])) }}"
  loop: "{{ slurm_slurm_packages | dict2items }}"
  when: slurm_enable is defined and slurm_enable.get(item.key, false) | bool

- name: install | Install required slurm packages
  tags: install
  ansible.builtin.dnf:
    name: "{{ slurm_pkglist | reject('eq', '') }}"
    install_weak_deps: false # avoids getting recommended packages
  when: slurm_pkglist is defined and slurm_pkglist | length > 0

- name: install | Install other packages
  tags: install
  ansible.builtin.dnf:
    name: "{{ slurm_packages }}"

- name: install | Create facts directory
  tags: install
  when: slurm_enable.get('slurmd', false) | bool
  ansible.builtin.file:
    path: /etc/ansible/facts.d/
    state: directory
    owner: root
    group: root
    mode: ugo=rwX

- name: install | Deploy slurmd topology facts script
  tags: install
  when: slurm_enable.get('slurmd', false) | bool
  ansible.builtin.copy:
    src: slurmd_topology.fact
    dest: /etc/ansible/facts.d/slurmd_topology.fact
    owner: root
    group: root
    mode: "0755"

- name: install | Refresh local Ansible facts on slurmd nodes
  tags: install
  when: slurm_enable.get('slurmd', false) | bool
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - local
