---

- name: Store role variables in hostvars
  set_fact:
    role_slurm_enable: "{{ role_slurm_enable }}"
    role_slurm_service: "{{ (role_slurm_enable.slurmd | bool) | ternary('slurmd',False) or omit }}"

- include: users.yml
  when: role_slurm_enable.runtime | bool

- include: db.yml
  when: role_slurm_db_host in hostvars
  delegate_to: "{{ role_slurm_db_host }}"
  delegate_facts: true
  run_once: true

- include: control.yml
  when: role_slurm_control_host in hostvars
  delegate_facts: true
  delegate_to: "{{ role_slurm_control_host }}"

- include: compute.yml
  when: role_slurm_enable.batch | bool

- include: runtime.yml
  when: role_slurm_enable.runtime | bool

- include: pam.yml
  when: role_slurm_enable.batch | bool

- block:
    - include: validate.yml
  delegate_to: "{{ groups.cluster_login | default([ role_slurm_control_host ]) | first }}"
  tags: validate
  run_once: true
  when: role_slurm_run_validate | bool
...
