---
- name: Store role variables in hostvars
  ansible.builtin.set_fact:
    role_slurm_enable: "{{ role_slurm_enable }}"
    role_slurm_service: "{{ (role_slurm_enable.slurmd | bool) | ternary('slurmd', False) or omit }}"


- name: Include users.yml tasks
  ansible.builtin.include_tasks: users.yml
  when: role_slurm_enable.runtime | bool

- name: Include db.yml tasks
  ansible.builtin.include_tasks: db.yml
  args:
    apply:
      delegate_to: "{{ role_slurm_db_host }}"
      delegate_facts: true
  when: role_slurm_db_host in hostvars
  run_once: true

- name: Include control.yml tasks
  ansible.builtin.include_tasks: control.yml
  args:
    apply:
      delegate_to: "{{ role_slurm_control_host }}"
      delegate_facts: true
  when: role_slurm_control_host in hostvars
  run_once: true

- name: Include rest.yml tasks
  ansible.builtin.include_tasks: rest.yml
  args:
    apply:
      delegate_to: "{{ role_slurm_control_host }}"
      delegate_facts: true
  when: role_slurm_enable_rest | bool
  run_once: true

- name: Include compute.yml tasks
  ansible.builtin.include_tasks: compute.yml
  when: role_slurm_enable.batch | bool

- name: Include runtime.yml tasks
  ansible.builtin.include_tasks: runtime.yml
  when: role_slurm_enable.runtime | bool

- name: Include pam.yml tasks
  ansible.builtin.include_tasks: pam.yml
  when: role_slurm_enable.batch | bool

- name: Include validtion.yml tasks
  ansible.builtin.include_tasks: validate.yml
  args:
    apply:
      delegate_to: "{{ groups.cluster_login | default([role_slurm_control_host]) | first }}"
  when: role_slurm_run_validate | bool
  tags: validate
  run_once: true
