---
- name: munge | Write Munge key
  tags: always
  ansible.builtin.copy:
    content: "{{ slurm_munge_key | b64decode }}"
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: "0400"
  register: _slurm_munge_key_copy


- name: munge | Ensure Munge service is running
  tags: always
  ansible.builtin.service:
    name: munge
    state: "{{ 'restarted' if _slurm_munge_key_copy.changed else 'started' }}"
    enabled: true
