---

- name: pam | Add pam_slurm_adopt and pam_access to SSH PAM configuration
  tags:
    - pam
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    insertafter: '^account\s+include\s+password-auth'
    block: |
      account    sufficient   pam_slurm_adopt.so action_no_jobs=deny action_unknown=newest action_adopt_failure=deny action_generic_failure=deny
      account    required     pam_access.so
    backup: true


- name: pam | Fix pam_systemd lines in /etc/pam.d/ auth files
  tags:
    - pam
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^\s*#?\s*-session\s+optional\s+pam_systemd\.so\s*$'
    line: "#-session     optional      pam_systemd.so"
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth


# - name: SELINUX fix context on /var/spool/slurm
#   ansible.builtin.command: /sbin/restorecon -Fvri "{{ slurm_spool_dir }}"
#   changed_when: true

# - name: Stop, disable, mask systemd-logind
#   ansible.builtin.systemd:
#     name: systemd-logind
#     state: stopped
#     enabled: false
#     masked: true

- name: pam | Fix /etc/security/access.conf
  tags:
    - pam
  ansible.builtin.blockinfile:
    path: /etc/security/access.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      {% for item in slurm_ssh_access | default([]) %}+:{{ item }}:ALL
      {% endfor %}
      {% if ansible_user is defined %}+:{{ ansible_user }}:ALL
      {% endif %}
      -:ALL:ALL
