---
# Setup slurm_adopt and restrict ssh access
- name: Copy /etc/pam.d/sshd
  ansible.builtin.copy:
    mode: "0644"
    src: files/pam.d/{{ item }}
    dest: /etc/pam.d
  loop:
    - sshd
    - slurm

- name: Fix pam_systemd lines in /etc/pam.d/ auth files
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: pam_systemd
    state: absent
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth

- name: Install selinux rpm
  ansible.builtin.yum:
    name: slurm_pam_slurm_adopt_selinux
    state: present
  when: role_slurm_adopt_selinux | bool

- name: SELINUX fix context on /var/spool/slurm
  ansible.builtin.command: /sbin/restorecon -Fvri /var/spool/slurm
  when: role_slurm_adopt_selinux | bool
  changed_when: true

- name: Stop, disable, mask systemd-logind
  ansible.builtin.systemd:
    name: systemd-logind
    state: stopped
    enabled: false
    masked: true

- name: Fix /etc/security/access.conf
  ansible.builtin.blockinfile:
    path: /etc/security/access.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      {% for item in role_slurm_ssh_access | default([]) %}+:{{ item }}:ALL
      {% endfor %}
      {% if ansible_user is defined %}+:{{ ansible_user }}:ALL
      {% endif %}
      +:root:cron crond
      -:ALL:ALL
