---

- name: pam | Add pam_slurm_adopt and pam_access to SSH PAM configuration
  tags:
    - pam
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sshd
    insertafter: '^account\s+include\s+password-auth'
    block: |
      account    sufficient   pam_slurm_adopt.so action_no_jobs=deny action_unknown=newest action_adopt_failure=deny action_generic_failure=deny
      account    required     pam_access.so
    backup: true


- name: pam | Fix pam_systemd lines in /etc/pam.d/ auth files
  tags:
    - pam
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: '^\s*#?\s*-session\s+optional\s+pam_systemd\.so\s*$'
    line: "#-session     optional      pam_systemd.so"
  loop:
    - /etc/pam.d/system-auth
    - /etc/pam.d/password-auth


# - name: SELINUX fix context on /var/spool/slurm
#   ansible.builtin.command: /sbin/restorecon -Fvri "{{ slurm_spool_dir }}"
#   changed_when: true

# - name: Stop, disable, mask systemd-logind
#   ansible.builtin.systemd:
#     name: systemd-logind
#     state: stopped
#     enabled: false
#     masked: true

- name: pam | Fix /etc/security/access.conf
  tags:
    - pam
  ansible.builtin.blockinfile:
    path: /etc/security/access.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      {% for item in slurm_ssh_access | default([]) %}+:{{ item }}:ALL
      {% endfor %}
      {% if ansible_user is defined %}+:{{ ansible_user }}:ALL
      {% endif %}
      -:ALL:ALL

- name: pam | Check if SELinux module is installed
  tags:
    - pam
  ansible.builtin.command:
    cmd: semodule -l | grep -q '^pam_slurm_adopt'
  register: slurm_semodule_check
  failed_when: false
  changed_when: false
  when: ansible_selinux.status == "enabled"

- name: pam | Configure SELinux Policy for SLURM adopt
  tags:
    - pam
  when: ansible_selinux.status == "enabled" and slurm_semodule_check.rc != 0
  block:
    - name: pam | Create temporary directory for SELinux policy
      tags:
        - pam
      ansible.builtin.tempfile:
        state: directory
        suffix: selinux
      register: slurm_selinux_tempdir

    - name: pam | Copy SELinux policy file
      tags:
        - pam
      ansible.builtin.copy:
        src: pam_slurm_adopt.te
        dest: "{{ slurm_selinux_tempdir.path }}/pam_slurm_adopt.te"
        mode: '0644'

    - name: pam | Package SELinux policy module
      tags:
        - pam
      ansible.builtin.command:
        cmd: "make -f /usr/share/selinux/devel/Makefile pam_slurm_adopt.pp"
        creates: "{{ slurm_selinux_tempdir.path }}/pam_slurm_adopt.pp"
      args:
        chdir: "{{ slurm_selinux_tempdir.path }}"

    - name: pam | Install SELinux policy module
      tags:
        - pam
      ansible.builtin.command:
        cmd: "semodule -i {{ slurm_selinux_tempdir.path }}/pam_slurm_adopt.pp"
      register: slurm_semodule_install
      changed_when: slurm_semodule_install.rc == 0

    - name: pam | Cleanup temporary directory
      tags:
        - pam
      ansible.builtin.file:
        path: "{{ slurm_selinux_tempdir.path }}"
        state: absent
