---
- name: powersave | Deploy resume program
  ansible.builtin.template:
    src: "{{ slurm_power_save_resume_program }}"
    dest: /etc/slurm/{{ slurm_power_save_resume_program | basename }}
    owner: slurm
    group: slurm
    mode: "0755"
  notify: Restart slurmctld
  when: slurm_power_save_resume_program
  tags:
    - reconfigure
    - powersave

- name: powersave | Deploy suspend program
  ansible.builtin.template:
    src: "{{ slurm_power_save_suspend_program }}"
    dest: /etc/slurm/{{ slurm_power_save_suspend_program | basename }}
    owner: slurm
    group: slurm
    mode: "0755"
  notify: Restart slurmctld
  when: slurm_power_save_suspend_program
  tags:
    - reconfigure
    - powersave
