---
- name: rest | Create Slurm Rest Daemon user
  ansible.builtin.user:
    name: slurmrestd
    comment: SLURM REST daemon user
    system: true
    shell: /sbin/nologin
  tags: rest

- name: rest | Create socket folder
  ansible.builtin.file:
    state: directory
    path: /var/run/slurmrestd
    owner: slurmrestd
    group: slurmrestd
    mode: "755"
  tags: rest

- name: rest | Ensure Slurmrest service is enabled
  ansible.builtin.service:
    name: slurmrestd
    enabled: "{{ slurm_service_enabled | bool }}"
    state: "{{ 'started' if slurm_service_started | bool else 'stopped' }}"
  tags: rest
