---
- name: Create slurm group
  ansible.builtin.group:
    name: slurm
    gid: 202
    system: true

- name: Create slurm user
  ansible.builtin.user:
    name: slurm
    comment: SLURM resource manager
    system: true
    shell: /sbin/nologin
    uid: 202
    group: slurm
