# Make sure that OpenHPC repo is available
---
- name: Install epel-release package
  hosts: all
  tasks:
    - name: Install epel-release repo
      package:
        name:
          - epel-release
          - which
          - tcsh
          - sudo
        state: present

    - block:
        - name: Install dnf config-manager plugin
          package:
            name:
              - dnf-plugins-core
            state: installed

        - name: Enable the EPEL PowerTools repository
          command: "dnf config-manager --set-enabled powertools"
      when: ansible_distribution_file_variety == 'RedHat' and ansible_distribution_major_version == '8'
