---
- name: Install epel-release package
  hosts: all
  tasks:
    - name: Install epel-release repo
      ansible.builtin.package:
        name:
          - epel-release
          - which
          - tcsh
          - sudo
        state: present

    - name: Install dnf config-manager plugin on RHEL 8.x
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
      block:
        - name: Install dnf config-manager plugin
          ansible.builtin.package:
            name:
              - dnf-plugins-core
            state: installed

        - name: Enable the EPEL PowerTools repository
          ansible.builtin.command: dnf config-manager --set-enabled powertools
          changed_when: true
