---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    image: docker.artifactory.imp.ac.at/it/molecule/centos7:latest
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
  - name: instance-ubi8.8-1-${INSTANCE_ID:-local}
    image: docker.artifactory.imp.ac.at/vbc/ubi8/tde:8.8-1
    privileged: true
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
