# tasks file for role-lmod
---
- name: Check variables
  assert:
    that:
      - role_lmod_base_folder | length > 0
      - role_lmod_build_env | length > 0

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Retrieve mount information for module path
  command: mountpoint -q {{ role_lmod_base_folder }}
  register: volume_stat
  failed_when: false
  changed_when: false

- name: Determine if system module path is a shared filesystem
  set_fact:
    role_lmod_shared_module_fs: "{{ volume_stat.rc == 0 }}"

- include: lmod.yml

- include: easybuild.yml
