#!/usr/bin/env bash

if [ $# -ne 2 ]
then
    echo "usage: $0 source_folder destination_folder"
    exit 1
fi

if [ ! -d "$1" ]
then
    echo "$1 not a folder, exiting"
    exit 1
fi
if [ ! -d "$2" ]
then
    echo "$2 not a folder, exiting"
    exit 1
fi

module load mpifileutils/0.9.1-foss-2018b

export OMPI_MCA_btl="tcp,self"
time srun --mpi=pmi2 --qos=short -n 20 --ntasks-per-node=1 --cpus-per-task=1 dcp $1 $2
