---
# tasks file for role-nhc
- name: install NHC from a yum repo
  package: pkg=lbnl-nhc

- name: template in nhc.conf
  template: src=nhc.conf.j2 dest=/etc/nhc/nhc.conf backup=yes mode=0644
  tags: nhc_reconfigure

- name: template in extra nhc scripts
  template: src={{ item }} dest=/etc/nhc/scripts/{{ item }} backup=yes mode=0644
  with_items: "{{ nhc_scripts }}"
  when: nhc_scripts.0 | length > 0
  tags: nhc_reconfigure
