---
# tasks file for role-nhc
- name: Install NHC from a yum repo
  ansible.builtin.package:
    pkg: lbnl-nhc

- name: Template in nhc.conf
  ansible.builtin.template:
    src: nhc.conf.j2
    dest: /etc/nhc/nhc.conf
    backup: true
    mode: "0644"
  tags: nhc_reconfigure

- name: Template in extra nhc scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /etc/nhc/scripts/{{ item }}
    backup: true
    mode: "0644"
  loop: "{{ nhc_scripts }}"
  when: nhc_scripts.0 | length > 0
  tags: nhc_reconfigure

- name: Overwrite watchdog timeout
  ansible.builtin.copy:
    content: |
      TIMEOUT={{ nhc_watchdog_timeout }}
    dest: /etc/sysconfig/nhc
    mode: "0644"
    owner: root
    group: root
  when: nhc_watchdog_timeout
  tags: nhc_reconfigure

- name: Remove watchdog timeout
  ansible.builtin.file:
    dest: /etc/sysconfig/nhc
    state: absent
  when: not nhc_watchdog_timeout
  tags: nhc_reconfigure
