---
- name: Import install.yml tasks
  ansible.builtin.import_tasks: install.yml

- name: Import dcbx.yml tasks
  ansible.builtin.import_tasks: dcbx.yml

- name: Import configure.yml tasks
  ansible.builtin.import_tasks: configure.yml
