---
# tasks for checking is a node is enrolled
- name: Check if machine is enrolled
  ansible.builtin.shell: set -o pipefail; realm list | grep {{ domain_to_join.name }}
  register: realmd_bound
  changed_when: false
  failed_when: realmd_bound.rc != 0
  ignore_errors: true
