---
# tasks for enrolling a node
- name: Install realmd package
  ansible.builtin.package:
    name: "{{ role_sssd_packages }}"
    state: present

- name: Copy realmd.conf
  become: true
  ansible.builtin.template:
    src: templates/realmd.conf.j2
    dest: /etc/realmd.conf
    mode: "0644"
  notify: restart realmd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- ansible.builtin.include_tasks: check.yml
- name: Enroll machine in AD
  ansible.builtin.shell: >
    set -o pipefail;
    echo '{{ role_sssd_ad_password  }}' |
    realm join --membership-software adcli --unattended --verbose -U {{ domain_to_join.ad_username }} {{ domain_to_join.name }}
  register: enroll_result
  failed_when: enroll_result.rc > 0
  changed_when: true
  when: realmd_bound is failed

- when: role_sssd_allowed_groups | length > 0
  block:
    - name: Change access_provider to simple
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/{{ domain_to_join.name }}
        option: access_provider
        value: simple
        mode: "0600"
      notify: restart sssd

    - name: Add groups to simple_allow_groups
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/{{ domain_to_join.name }}
        option: simple_allow_groups
        value: "{{ role_sssd_allowed_groups | default([]) | join(',') }}"
        mode: "0600"
      notify: restart sssd

- name: Enable password authentication in ssh config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication yes
    mode: "0600"
  notify: restart sshd

- name: Set override homedir in sssd.conf
  community.general.ini_file:
    path: /etc/sssd/sssd.conf
    section: domain/{{ domain_to_join.name }}
    option: override_homedir
    value: "{{ role_sssd_override_homedir }}"
    mode: "0600"
  notify: restart sssd
  when: role_sssd_override_homedir is defined

- when: role_sssd_use_ssh_key
  block:
    - name: Set LDAP extra attributes for ssh key
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/{{ domain_to_join.name }}
        option: ldap_user_extra_attrs
        value: altSecurityIdentities
        mode: "0600"
      notify: restart sssd

    - name: Set LDAP user public key field
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: domain/{{ domain_to_join.name }}
        option: ldap_user_ssh_public_key
        value: altSecurityIdentities
        mode: "0600"
      notify: restart sssd

    - name: Add ssh to sssd services
      community.general.ini_file:
        path: /etc/sssd/sssd.conf
        section: sssd
        option: services
        value: nss, pam, ssh
        mode: "0600"
      notify: restart sssd

    - name: Set AuthorizedKeysCommand to sss command
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^AuthorizedKeysCommand
        insertafter: ^#AuthorizedKeysCommand
        line: AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
        state: present
        mode: "0600"
      notify: restart sshd

    - name: Set AuthorizedUsername to nobody
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        insertafter: ^#AuthorizedKeysCommandUser
        regexp: ^AuthorizedKeysCommandUser
        line: AuthorizedKeysCommandUser nobody
        state: present
        mode: "0600"
      notify: restart sshd
