---
# tasks for un-enrolling a node

- include_tasks: check.yml

- name: Un-enroll machine from AD
  shell: >
    set -o pipefail;
    echo '{{ role_sssd_ad_password  }}' | realm leave --unattended --verbose -U {{ domain_to_join.ad_username }} {{ domain_to_join.name }}
  register: unenroll_result
  failed_when: unenroll_result.rc > 0
  changed_when: true
  when: realmd_bound is not failed
