---
# main tasks for role-sssd
- name: Check that password for realm_join user is specified
  ansible.builtin.assert:
    that:
      - role_sssd_ad_password is defined
  when: role_sssd_present

- name: Retrieve domain to join
  ansible.builtin.set_fact:
    domain_to_join: "{{ role_sssd_domains[role_sssd_domain] }}"

- name: Enroll machine
  ansible.builtin.include_tasks: enroll.yml
  when: role_sssd_present

- name: Un-enroll machine
  ansible.builtin.include_tasks: leave.yml
  when: not role_sssd_present
