---
# defaults file for role-nhc

# Variables below are used inside the template for nhc.conf
nhc_short_hostname: true
nhc_hw_swap_free: 0
nhc_hw_mem_free: "1MB"
nhc_hw_eth: "eth0"
nhc_hw_mcelog: true

# By default allow 100 corrected errors/24h
nhc_mcelog_max_corrected_rate: 100
nhc_fs_mount_check: []
nhc_fs_mount_default_opts: '/(^|,)vers=3(,|$)/'
gpu: false

# sssd check which group to pick random user from
nhc_group_random_user: "role.cbe.users"

nhc_checks:
 - { match: "*", name: "check_reboot_slurm", arguments: "" }
 - { match: "*", name: "check_goss", arguments: "" }
 - { match: "*", name: "check_id_from_group", arguments: "{{ nhc_group_random_user }}" }
 - { match: "*-g*-*", name: "check_nvidia_smi_page_retirement", arguments: "" }
