---
galaxy_info:
  author: Uemit Seren
  description: Role to install a SLURM cluster
  company: VBC
  namespace: clip

  license: MIT

  min_ansible_version: 2.6


  platforms:
    - name: Centos
      versions:
        - 7
    - name: RedHat
      versions:
        - 7

  galaxy_tags: []

dependencies: []
