---
galaxy_info:
  author: Uemit Seren
  description: Role to install a SLURM cluster
  company: VBC
  namespace: clip

  license: MIT

  min_ansible_version: "2.8"

  platforms:
    - name: EL
      versions:
        - "7"
        - "8"

  galaxy_tags: []
dependencies: []
