---
# handlers file for sssd_ldap
- name: restart realmd
  service:
    name: realmd
    state: restarted

- name: restart sssd
  service:
    name: sssd
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
