---
# handlers file for sssd_ldap
- name: restart realmd
  ansible.builtin.service:
    name: realmd
    state: restarted

- name: restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
