---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert BeeGFS services are running and enabled
      ansible.builtin.assert:
        that:
          - "item + '.service' in ansible_facts.services"
          - "ansible_facts.services[item + '.service'].state == 'running'"
          - "ansible_facts.services[item + '.service'].status == 'enabled'"
      loop:
        - beegfs-meta
        - beegfs-mgmtd
      loop_control:
        label: "{{ item }}"

    - name: Check BeeGFS mount paths exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: beegfs_mount_path
      loop:
        - /mnt/beegfs
        - /mnt/beegfs-second

    - name: Assert BeeGFS mount paths exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
      loop: "{{ beegfs_mount_path.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Get filesystem type for BeeGFS mount paths
      ansible.builtin.command: findmnt -n -o FSTYPE --target {{ item }}
      register: beegfs_mount_fstype
      changed_when: false
      loop:
        - /mnt/beegfs
        - /mnt/beegfs-second

    - name: Assert BeeGFS mount paths filesystem is beegfs
      ansible.builtin.assert:
        that:
          - item.rc == 0
          - item.stdout == 'beegfs'
      loop: "{{ beegfs_mount_fstype.results }}"
      loop_control:
        label: "{{ item.item }}"
