---
- name: Cleamup
  hosts: all
  gather_facts: false
  vars_files:
    - vars/vars.yml
    - ../../vars/main.yml

  tasks:
    - name: Import variable checks
      ansible.builtin.import_tasks: tasks/test_vars.yml

    - name: Install infoblox-client pip
      delegate_to: localhost
      ansible.builtin.pip:
        name: infoblox-client

    - name: InfoBlox destroy test host record
      delegate_to: localhost
      community.general.nios_host_record:
        name: "{{ role_dns_hostname }}"
        provider: "{{ nios_provider }}"
        state: absent
        view: intern
        comment: This is a molecule role-dns test instance
      register: cleanup_result

# vim: sts=2:ai:list
