# setup a host certificate
---
- name: Sectigo ACME call for challenge
  become: false
  acme_certificate:
    acme_version: 2
    account_uri: '{{ role_certificate_provider.account_uri }}'
    acme_directory: '{{ role_certificate_provider.directory }}'
    challenge: "dns-01"
    modify_account: false
    remaining_days: "{{ role_certificate_renew_days }}"
    account_key_content: "{{ role_certificate_provider.account_key }}"
    csr: "{{ new_csr.filename }}"
    fullchain_dest: "{{ cert_basepath }}.crt"
  register: sectigo_acme_challenge
  connection: local
  delegate_to: localhost

- name: create TXT DNS records with challenge
  become: false
  nios_txt_record:
    name: "{{ item.key }}"
    text: "{{ item.value | first }}"
    ttl: 60
    state: present
    view: extern
    provider: "{{ role_certificate_nios_provider }}"
  connection: local
  delegate_to: localhost
  loop: "{{ sectigo_acme_challenge.challenge_data_dns | default({}) | dict2items }}"
  when: sectigo_acme_challenge is changed

- name: Sectigo ACME renew certificate with challenge
  become: false
  acme_certificate:
    acme_version: 2
    account_uri: '{{ role_certificate_provider.account_uri }}'
    acme_directory: '{{ role_certificate_provider.directory }}'
    modify_account: false
    challenge: "dns-01"
    data: "{{ sectigo_acme_challenge }}"
    remaining_days: "{{ role_certificate_renew_days }}"
    account_key_content: "{{ role_certificate_provider.account_key }}"
    csr: "{{ new_csr.filename }}"
    fullchain_dest: "{{ cert_basepath }}.crt"
  register: sectigo_acme_cert_result
  connection: local
  delegate_to: localhost
  when: sectigo_acme_challenge is changed

- name: cleanup TXT DNS records
  become: false
  nios_txt_record:
    name: "{{ item.key }}"
    text: "{{ item.value | first }}"
    state: absent
    view: extern
    provider: "{{ role_certificate_nios_provider }}"
  loop: "{{ sectigo_acme_challenge.challenge_data_dns | default({}) | dict2items }}"
  when: sectigo_acme_challenge is changed
  connection: local
  delegate_to: localhost
...
