---
- name: install | Include repo.yml
  ansible.builtin.include_tasks: repo.yml
  when: doca_use_upstream_repo | bool

- name: Install DKMS and kernel development packages
  ansible.builtin.dnf:
    name:
      - dkms
      - gcc
      - make
      - perl
      - mokutil
    state: present
  become: true


- name: install | Install DOCA packages
  ansible.builtin.dnf:
    name: "{{ doca_profile }}"
  register: _doca_install
  notify: Reboot machine

- name: install | Notify handlers
  ansible.builtin.meta: flush_handlers

# - name: Load the new driver
#   ansible.builtin.command: /etc/init.d/openibd restart
