---

- name: install | Determine running kernel
  ansible.builtin.command: uname -r # e.g. 4.18.0-513.18.1.el8_9.x86_64
  register: doca_ofed_loaded_kernel
  changed_when: false

- name: install | Determine newest installed kernel
  ansible.builtin.shell: |
    set -o pipefail
    dnf list --installed kernel \
      | awk '$1 ~ /^kernel\./ {print $2}' \
      | sed -E 's/\.[^.]+$//' \
      | sort -V \
      | tail -n 1
  args:
    executable: /bin/bash
  register: doca_ofed_dnf_kernels_newest
  changed_when: false


- name: install | Check current kernel is newest installed
  ansible.builtin.assert:
    that: _ofed_kernel_current == doca_ofed_dnf_kernels_newest.stdout
    fail_msg: "Kernel {{ doca_ofed_loaded_kernel.stdout }} is loaded but newer {{ doca_ofed_dnf_kernels_newest.stdout }} is installed: consider rebooting?"
  vars:
    _ofed_kernel_current: >-
      {{ doca_ofed_loaded_kernel.stdout | regex_replace('\.(?:.(?!\.))+$', '') | regex_replace('\.(?:.(?!\.))+$', '') }}
    # dnf line format e.g. "kernel.x86_64  4.18.0-513.18.1.el8_9   @baseos  "

- name: install | Install matching kernel-devel package
  ansible.builtin.dnf:
    name: "kernel-devel-{{ doca_ofed_loaded_kernel.stdout | trim }}"

- name: install | Include repo.yml
  ansible.builtin.include_tasks: repo.yml
  when: doca_use_upstream_repo | bool

- name: install | Install doca-extra package
  ansible.builtin.dnf:
    name: doca-extra

- name: install | Check if DNF doca-kernel repo already exists
  ansible.builtin.command: /usr/bin/dnf repolist doca-kernel-"{{ ansible_kernel }}"
  register: _doca_kernel_repo_check
  failed_when: false
  changed_when: false

- name: install | Install DOCA Kernel repo
  when: "'doca-kernel-' not in _doca_kernel_repo_check.stdout"
  block:
    - name: install | Build DOCA kernel modules
      ansible.builtin.command:
        cmd: /opt/mellanox/doca/tools/doca-kernel-support
      register: _doca_kernel_build
      changed_when: true

    - name: install | Find generated doca-kernel-repo
      ansible.builtin.shell: 'find /tmp/DOCA.* -name doca-kernel-repo-*'
      register: _doca_kernel_repo # e.g. /tmp/DOCA.WVMchs2QWo/doca-kernel-repo-24.10.1.1.4.0-1.kver.5.14.0.427.31.1.el9.4.x86.64.x86_64.rpm
      changed_when: false

    - name: install | Create dnf cache
      ansible.builtin.command: dnf makecache
      changed_when: false

    - name: install | Install DOCA repository package
      ansible.builtin.dnf:
        name: "{{ _doca_kernel_repo.stdout }}"
        disable_gpg_check: true

- name: install | Install DOCA packages
  ansible.builtin.dnf:
    name: "{{ doca_profile }}"
  register: _doca_install
  notify: Reboot machine

- name: install | Cleanup DOCA build directories
  ansible.builtin.file:
    state: absent
    path: "{{ (_doca_kernel_repo.stdout | split('/'))[:3] | join('/') }}" # leading / means 1st element of split list is ''
  when: "not (_doca_kernel_build.skipped | default(false) | bool)"

- name: install | Update initramfs
  ansible.builtin.command:
    cmd: dracut -f
  register: _doca_dracut
  failed_when: _doca_dracut.stderr != '' # appears rc is always 0
  when: "not (_doca_kernel_build.skipped | default(false) | bool)"
  changed_when: true

- name: install | Notify handlers
  ansible.builtin.meta: flush_handlers

# - name: Load the new driver
#   ansible.builtin.command: /etc/init.d/openibd restart
