---
# currently not used
# - name: repo | Imort DOCA GPG key
#   ansible.builtin.rpm_key:
#     key: "{{ doca_repo_url }}GPG-KEY-Mellanox.pub"
#     state: present

- name: repo | Install DOCA repo
  ansible.builtin.yum_repository:
    name: doca
    file: doca
    description: DOCA Online Repo
    baseurl: "{{ doca_repo_url }}"
    enabled: true
    gpgcheck: false # not used in RHEL
