---
# handlers file for role-container
# order is important: execution by order of definition, not order of notify
- name: Restart container service {{ role_container_service.name }}
  become: true
  ansible.builtin.systemd:
    name: podman_{{ role_container_service.name }}
    state: restarted
    daemon_reload: true
    enabled: true
- name: Prune podman images # i.e. dangling (untagged), unused
  become: true
  # prune -f --all is required, to ged rid of older version tagged images
  ansible.builtin.shell: /usr/bin/podman image prune -f --all
  register: prune_result
  changed_when: prune_result.stdout_lines | length > 0
