---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install sshd
      yum:
        name: openssh-server
        state: present

    - name: Enable sshd
      service:
        name: sshd
        state: started
