---
- name: Restart Munge service
  ansible.builtin.service:
    name: munge
    state: restarted
  when: role_slurm_service_enabled | bool
  tags: always

- name: Restart slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    state: restarted
  delegate_to: "{{ role_slurm_db_host }}"
  run_once: true
  when: role_slurm_db_host in hostvars
  tags: always

- name: Restart slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: restarted
  delegate_to: "{{ role_slurm_control_host }}"
  run_once: true
  when:
    - not (role_slurm_reconfigure | bool)
  tags: always

- name: Restart slurmrestd
  ansible.builtin.systemd:
    name: slurmrestd
    daemon_reload: true
    state: restarted
  delegate_to: "{{ role_slurm_control_host }}"
  run_once: true
  when:
    - not (role_slurm_reconfigure | bool)
  tags: always

- name: Restart SLURM service
  ansible.builtin.service:
    name: "{{ role_slurm_service }}"
    state: restarted
  when:
    - role_slurm_service is not none
    - role_slurm_service_enabled | bool
    - not (role_slurm_reconfigure | bool)
  tags: always

- name: Restart mariadb service
  ansible.builtin.service:
    name: mariadb
    state: restarted
  delegate_to: "{{ role_slurm_db_host }}"
  run_once: true
  tags: always

- name: Reconfigure
  listen: Restart SLURM service
  run_once: true
  delegate_to: "{{ role_slurm_control_host }}"
  ansible.builtin.command: /bin/scontrol reconfigure
  tags: always
  changed_when: true
