---
slurm_slurm_packages:
  control:
    - "slurm-slurmctld"
    - "slurm-example-configs"
    - "s-nail"
    - "lua" # used to compoile check job_submit.lua
  batch:
    "{{
      ['slurm',
        'slurm-pam_slurm',
        'slurm-libpmi',
        'selinux-policy-devel'] +
      (['slurm-pam-slurm-adopt-selinux'] if (slurm_adopt_selinux | bool) else [])
    }}"
  runtime:
    - "slurm"
    - "slurm-slurmd"
    - "munge"
  database:
    - "slurm-slurmdbd"
    - "mariadb-server"
    - "python3-PyMySQL"
  rest:
    - "slurm-slurmrestd"
slurm_packages:
  - slurm-libpmi
