---
# depending on the var setting, it will run server or client
- name: check syslog mode validity
  ansible.builtin.assert:
    that:
      - role_syslog_mode in ['server', 'client']
    success_msg: running syslog deployment for {{ role_syslog_mode }}
    fail_msg: "var 'role_syslog_mode' must be one of: 'client', 'server'"

- name: install additional packages (logrotate, xz, rsyslog modules)
  become: true
  ansible.builtin.yum:
    name: logrotate,xz,rsyslog
    state: present

- name: setting up syslog
  ansible.builtin.include_tasks: "{{ role_syslog_mode }}.yml"
