---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    image: centos:7
    pre_build_image: true
    privileged: true
  - name: instance-centos8-${INSTANCE_ID:-local}
    image: quay.io/centos/centos:centos8
    pre_build_image: true
    privileged: true
  - name: instance-stream8-${INSTANCE_ID:-local}
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
