---
role_certificate_hostname: "{{ inventory_hostname }}"
role_certificate_aliases:
role_certificate_tls_dir: /srv/certificates/
role_certificate_renew_days: 31
role_certificate_provider:
  type: acme
  directory: "https://acme.sectigo.com/v2/OV"
  account_id: "sectigo account_id"
  account_uri: "https://acme.sectigo.com/v2/OV/account/< sectigo account_id>"
  account_key: " account_key from 1Password | replace('\\n', '\n') "
role_certificate_nios_provider:
  host:
  username:
  password:
# Sectigo might take a little longer (default is 10 sec)
role_certificate_acme_timeout: 60
