---
- name: Prepare
  hosts: all
  vars:
    role_sssd_allowed_groups: [is.grp]
    role_sssd_domain: TESTING
    ad_password: "{{ lookup('onepassword', 'svc_realmd_test_join', vault='accounts', master_password=onepass_password, secret_key=onepass_secret_key, subdomain=onepass_domain,\
      \ username=onepass_email) }}"
  tasks:
    - name: Install sshd
      ansible.builtin.yum:
        name: openssh-server
        state: present
    - name: Include sssd role
      ansible.builtin.include_role:
        name: sssd
      vars:
        role_sssd_domain: TESTING
        role_sssd_ad_password: "{{ ad_password }}"
