---
# vars file for role-dns
#
nios_provider:
  host: ns.imp.ac.at
  username: svc_infoblox_ansible
  password: "{{ lookup('onepassword', 'linux_baseline', section='dns-nios', field='password', vault='hosts', \
    service_account_token=lookup('ansible.builtin.env', 'OP_SERVICE_ACCOUNT_TOKEN')) }}"

# vim: sts=2:ai:list
