---
# handlers file for clip.hpc.smartctl_exporter
- name: Restart smartctl_exporter
  ansible.builtin.systemd:
    name: smartctl_exporter
    state: restarted
    daemon_reload: true
  become: true
