---
# tasks file for role-cuda
- name: Configure GPU driver
  when: role_cuda_gpu
  block:
    - name: Make sure that kernel headers and development packages are installed
      ansible.builtin.yum:
        name:
          - gcc
          - kernel-devel-{{ ansible_kernel }}
          - kernel-headers-{{ ansible_kernel }}
        state: present

    - name: Install Cuda drivers
      ansible.builtin.yum:
        name: "{{ role_cuda_packages }}"
        state: present

    - name: Retrieve nouveau kernel module status
      ansible.builtin.command: /usr/sbin/lsmod | /bin/grep nouveau
      register: nouveau_reg
      failed_when: false
      changed_when: false

    - name: Ensure nouveau is not loaded # noqa no-handler
      ansible.builtin.command: /usr/sbin/modprobe -r nouveau
      changed_when: true
      when: nouveau_reg.changed

    - name: Ensure that nvidia-persistenced is enabled and running
      ansible.builtin.service:
        name: nvidia-persistenced
        enabled: true
        state: started
