---
- name: Converge
  hosts: all
  tasks:
    - name: Include nhc role
      include_role:
        name: nhc
      vars:
        nhc_fs_mount_rw_scratch: false
        nhc_fs_mount_rw_home: false
        nhc_group_random_user: "nobody"
