---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-centos7-${INSTANCE_ID:-local}
    image: centos/systemd:latest
    hostname: cluster-centos7-login-0
    command: /sbin/init
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: instance-stream8-${INSTANCE_ID:-local}
    image: quay.io/centos/centos:stream8
    hostname: cluster-stream8-login-0
    command: /sbin/init
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
