---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubi8.8-1-${INSTANCE_ID:-local}
    image: docker.artifactory.imp.ac.at/vbc/ubi8/tde:8.8-1
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /tmp/instance-ubi8.8-1-${INSTANCE_ID:-local}:/var/lib/containers
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: update_image
verifier:
  name: testinfra
