---
- name: debug loop
  debug:
    msg: "Remove from {{ zone.zone | default(role_firewalld_default_zone, true) }} - {{ port }}"
  loop: "{{ removal.results[i].ansible_facts.port_list }}"
  loop_control:
    loop_var: port
  when: removal.results[i].ansible_facts.port_list

- name: Remove ports from zone
  firewalld:
    zone: "{{ zone.zone | default(role_firewalld_default_zone, true) }}"
    state: disabled
    port: "{{ port }}"
    immediate: true
    permanent: true
  loop: "{{ removal.results[i].ansible_facts.port_list }}"
  loop_control:
    loop_var: port
  when: removal.results[i].ansible_facts.port_list
  notify: "restart firewalld"
