---
- name: Debug loop
  ansible.builtin.debug:
    msg: Remove from {{ zone.zone | default(role_firewalld_default_zone, true) }} - {{ service }}
  loop: "{{ removal.results[i].ansible_facts.service_list }}"
  loop_control:
    loop_var: service
  when: removal.results[i].ansible_facts.service_list

- name: Remove services from zone
  ansible.posix.firewalld:
    zone: "{{ zone.zone | default(role_firewalld_default_zone, true) }}"
    state: disabled
    service: "{{ service }}"
    immediate: true
    permanent: true
  loop: "{{ removal.results[i].ansible_facts.service_list }}"
  loop_control:
    loop_var: service
  when: removal.results[i].ansible_facts.service_list
  notify: Restart firewalld
