---
# handlers file for role-firewalld
- name: Iptables-save
  ansible.builtin.shell: /sbin/iptables-save -t nat > /etc/baseline-iptables-save-nat
  listen: Restart firewalld

- name: Runtime-to-permanent
  ansible.builtin.command: /usr/bin/firewall-cmd --runtime-to-permanent
  listen: Restart firewalld

- name: Reload
  ansible.builtin.command: /usr/bin/firewall-cmd --reload
  listen: Restart firewalld

- name: Iptables-restore
  ansible.builtin.shell: /sbin/iptables-restore < /etc/baseline-iptables-save-nat
  listen: Restart firewalld

# vim: sts=2:ai:list
