---
dependency:
  name: galaxy
driver:
  name: docker
  network:
    - name: slurm-alma9-${INSTANCE_ID:-local}
      driver: bridge
platforms:
  - name: login-alma9-${INSTANCE_ID:-local}
    image: almalinux:9.4
    pre_build_image: true
    hostname: cluster-login-0
    networks:
      - name: slurm-alma9-${INSTANCE_ID:-local}
        links:
          - compute1-alma9-${INSTANCE_ID:-local}:cluster-compute1-0
          - compute2-alma9-${INSTANCE_ID:-local}:cluster-compute2-0
    groups:
      - cluster_login
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: compute1-alma9-${INSTANCE_ID:-local}
    hostname: cluster-compute1-0
    pre_build_image: true
    networks:
      - name: slurm-alma9-${INSTANCE_ID:-local}
    image: almalinux:9.4
    groups:
      - cluster_batch
    children:
      - cluster_compute1
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: compute2-alma9-${INSTANCE_ID:-local}
    hostname: cluster-compute2-0
    pre_build_image: true
    networks:
      - name: slurm-alma9-${INSTANCE_ID:-local}
    image: almalinux:9.4
    groups:
      - cluster_batch
    children:
      - cluster_compute2
    command: /sbin/init
    security_opts:
      - apparmor:unconfined
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: control-alma9-${INSTANCE_ID:-local}
    pre_build_image: true
    networks:
      - name: slurm-alma9-${INSTANCE_ID:-local}
        links:
          - compute1-alma9-${INSTANCE_ID:-local}:cluster-compute1-0
          - compute2-alma9-${INSTANCE_ID:-local}:cluster-compute2-0
    image: almalinux:9.4
    groups:
      - cluster_control
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: db-alma9-${INSTANCE_ID:-local}
    image: almalinux:9.4
    pre_build_image: true
    networks:
      - name: slurm-alma9-${INSTANCE_ID:-local}
    groups:
      - cluster_db
    command: /sbin/init
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
scenario:
  name: almalinux9
verifier:
  name: testinfra
  directory: ../resources/tests/
