---
slurm_cluster_name:
slurm_control_host:
slurm_db_host:
slurm_enable:
  control: false
  batch: false
  database: false
  runtime: false
  slurmd: false

slurm_reconfigure: false
slurm_spool_dir: /var/spool/slurmd
slurm_state_save_location: /var/spool/slurm


slurm_config: {}

slurm_default_config:
  # This only defines values which are not Slurm defaults
  SlurmctldHost: "{{ slurm_control_host }}"
  SlurmctldParameters: enable_configless,idle_on_node_suspend
  AuthAltTypes: auth/jwt
  AuthAltParameters: "{{ slurm_auth_alt_parameters | default(omit) }}"
  SlurmdSpoolDir: "{{ slurm_spool_dir }}"
  StateSaveLocation: "{{ slurm_state_save_location }}"
  ProctrackType: proctrack/cgroup
  # Want nodes that drop out of SLURM's configuration to be automatically
  # returned to service when they come back.
  ReturnToService: 2
  PropagateResourceLimitsExcept: MEMLOCK
  PrologFlags: contain,alloc,x11
  LaunchParameters: ulimit_pam_adopt
  X11Parameters: home_xauthority
  ScronParameters: enable
  TaskPlugin: "task/cgroup,task/affinity"
  HealthCheckInterval: 300
  SlurmctldTimeout: 300
  SchedulerType: sched/backfill
  SelectType: select/cons_tres
  SelectTypeParameters: CR_Core_Memory
  PriorityWeightPartition: 500
  PriorityType: priority/multifactor
  SlurmUser: slurm


  AccountingStorageHost: "{{ slurm_db_host }}"
  AccountingStorageType: "accounting_storage/slurmdbd"
  AccountingStorageUser: "{{ slurm_dbd_mysql_username }}"

  JobAcctGatherType: "jobacct_gather/cgroup"

  JobContainerType: job_container/tmpfs

  RebootProgram: /usr/sbin/reboot

slurm_service_enabled: true
slurm_service_started: "{{ slurm_service_enabled }}"

slurm_service:

slurm_partitions: []


slurm_qos: []

slurm_default_qos:
slurm_default_partition_mem: 4096
slurm_ssh_access: []
slurm_adopt_selinux: true


slurm_job_container_base_path: ""
slurm_job_container_shared_storage: false

# REST
slurm_rest_enable: false

slurm_login_only_nodes: ''

# Authentication
slurm_auth_alt_parameters: jwt_key=/etc/slurm/jwt.key
slurm_rest_jwt_key: ''
slurm_munge_key: ''

# Database configuration
slurm_dbd_mysql_database: slurm_acct_db
slurm_dbd_mysql_username: slurm
slurm_dbd_mysql_host: localhost
slurm_dbd_port: 6819
slurm_dbd_conf_debug_flags: ""
slurm_db_data_dir:
slurm_db_root_password: "{{ slurm_db_password }}"

# Auto detection
slurm_ram_multiplier: 0.95

slurm_power_save: false

slurm_job_submit_script:

slurm_job_submit_plugins: []
