heat_template_version: pike

description: >
  SoftwareConfig for RHEL Registration 

# Note extra parameters can be defined, then passed data via the
# environment parameter_defaults, without modifying the parent template
parameters:
  rhel_reg_activation_key:
    type: string
  rhel_reg_force:
    type: string
    default: ""
  rhel_reg_org:
    type: string
  rhel_reg_sat_url:
    type: string
  zone:
    type: string
    default: ""

resources:

  RHELRegistration:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped      
      config: 
        str_replace: 
          template: {get_file: scripts/rhel-registration.sh}
          params:
            $RHEL_REG_ACTIVATION_KEY: { get_param: rhel_reg_activation_key}
            $RHEL_REG_FORCE: { get_param: rhel_reg_force }
            $RHEL_REG_ORG: { get_param: rhel_reg_org }
            $RHEL_REG_SAT_URL: { get_param: rhel_reg_sat_url }
            $ZONE: { get_param: zone }
outputs:
  OS::stack_id:
    value: {get_resource: RHELRegistration}
