---
- name: Reboot server
  ansible.builtin.reboot:
    post_reboot_delay: 30

# handlers file for clip.hpc.rocev2
- name: Restart MLNX RoCE QoS service
  ansible.builtin.service:
    name: mlnx-roce-qos.service
    enabled: true
    state: "{{ rocev2_mlx_qos_service_state }}"
    daemon_reload: true
  become: true
