---
# vars file for clip.hpc.multirail
multirail_table_base: 201
multirail_rt_tables_file: /etc/iproute2/rt_tables.d/multirail.conf
# Location of the block written by earlier versions of this role, removed in favour of multirail_rt_tables_file
multirail_legacy_rt_tables_file: "{{ '/usr/share/iproute2/rt_tables' if ansible_facts['distribution_major_version'] == '10' else '/etc/iproute2/rt_tables' }}"
