---
# vars file for role-lmod
role_lmod_site_name: VBC
role_lmod_syshost: CLIP
role_lmod_build_env_name: build-env
role_lmod_system_folder: "{{ role_lmod_base_folder }}/system"
role_lmod_system_modules_folder: "{{ role_lmod_system_folder }}/modules"

role_lmod_core_folder: "{{ role_lmod_system_modules_folder }}/core"
role_lmod_rc_folder: "{{ role_lmod_system_modules_folder }}/.lmod"
role_lmod_build_env_install_folder: "{{ role_lmod_core_folder }}/{{ role_lmod_build_env_name }}"
role_lmod_easybuild_install_folder: "{{ role_lmod_base_folder }}/{{ role_lmod_build_env }}"
role_lmod_easybuild_git_work_folder: "{{ role_lmod_system_folder }}"
role_lmod_easybuild_easyconfig_folder: "{{ role_lmod_easybuild_git_work_folder }}/easyconfigs"
role_lmod_easybuild_cache_folder: "{{ role_lmod_base_folder }}/.lmodcache"
role_lmod_easybuild_github_repo: https://github.com/easybuilders/easybuild-easyconfigs.git
