---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-ubi8.4-1-${INSTANCE_ID:-local}
    image: docker.artifactory.imp.ac.at/vbc/ubi8/tde:8.4-1
    command: /usr/sbin/init
    privileged: true
    volumes:
      - "/tmp/instance-ubi8.4-1-${INSTANCE_ID:-local}:/var/lib/containers"
provisioner:
  name: ansible
scenario:
  name: files
verifier:
  name: testinfra
